/**
 * Created Date		: Sep 9, 2016
 * Developed By		: Chandra, Comity Designs, Inc.
 *
 * Function			: @description - Currency Exchange Rates
 * Support Email 	: email
 * Version			: 1.0
 *
 * Modification Log
 *
 * Developer Name			User Story				Date			Version 			Description
 *____________________________________________________________________________________________________
 *
 * Chandra					User Story				Sep 9, 2016			1.1					@description
 * 
 */
 //TO DO :Need to delete this class as moved to base.
public with sharing class CurrencyExchangeRateDataAccess {
	

}