/**
 * Created Date		: Oct 27, 2016
 * Developed By		: prashant, Comity Designs, Inc.
 *
 * Function			: @description - Description about the functionality that the class provides
 * Support Email 	: email
 * Version			: 1.0
 *
 * Modification Log
 *
 * Developer Name			User Story				Date			Version 			Description
 *____________________________________________________________________________________________________
 *
 * prashant					User Story				Oct 27, 2016			1.1					@description
 * 
 */
public Interface IScheduleDispatched {
     void executeScheduler(SchedulableContext sc);
}