/**
 * Created Date     : Dec 2, 2016
 * Developed By     : Nkonkar, Comity Designs, Inc.
 *
 * Function         : @description - Logic for Consolidating Opportunities in bulk
 * Support Email    : email
 * Version          : 1.0
 *
 * Modification Log
 *
 * Developer Name           User Story              Date            Version             Description
 *____________________________________________________________________________________________________
 *
 * Nkonkar                  User Story              Dec 2, 2016         1.1                 @description
 *
 */
public with sharing class REN_ConsolidateOpportunityHelper {
	
}