/**
 * Created Date		: Sep 17, 2018
 * Developed By		: Sheetal, Comity Designs, Inc.
 *
 * Function			: This is helper class for REN_SetOppSyncPendingStatusBatch
 * Support Email 	: email
 * Version			: 1.0
 *
 * Modification Log
 *
 * Developer Name			User Story				Date			Version 			Description
 *____________________________________________________________________________________________________
 *
 * Sheetal					User Story				Sep 17, 2018			1.1			This is helper class for REN_SetOppSyncPendingStatusBatch
 *
 */
public with sharing class REN_SetOppSyncPendingStatusHelper {

    

    /**
	 * @description One or more lines that provide an overview of the method
     * @param paramName A description of what the parameter does, use multiple @param for multiple params
     * @return A description of the return value from the method
     * @example Example code usage. This will be wrapped in tags to preserve whitespace
     */
	// MARK: Your method goes here
}