/**
 * Created Date		: Dec 2, 2016
 * Developed By		: Nkonkar, Comity Designs, Inc.
 *
 * Function			: @description - Batch will get schedule depending on Custom setting 'B'
 * Support Email 	: servicesource@comitydesigns.com
 * Version			: 1.0
 *
 * Modification Log
 *
 * Developer Name			User Story				Date			Version 			Description
 *____________________________________________________________________________________________________
 *
 * Nkonkar					User Story				Dec 2, 2016			1.1					@description
 *
 */
 
 public Interface REN_ConsolidateOppScheduleDispatch {
	
	  void execute(SchedulableContext sc);
	
 }